config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'example/show'

  get 'store/index'

  resources :products do

    get :who_bought, :on => :member

  end
  
  resources :products
  resource :example, only: [:show], controller: :example
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "store#index", as: 'store'
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :line_items
	has_many :orders, through: :line_items
	before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, allow_blank: true, format: {
		with: %r{\.(gif|jpg|png|jpeg|bmp)\Z}i,
		message: 'Неверный формат изображения используйте только gif|jpg|png|jpeg|bmp'
	}
	def self.latest
		Product.order(:updated_at).last
	end

	private

	    # убеждаемся в отсутствии товарных позиций, которые дают ссылку на этот товар

    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Сужествуют товарные позиции')
        return false
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
  
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
    
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Редактироване товара</h1>

<%= render 'form', product: @product %>

<%= link_to 'Просмотр', @product %> |
<%= link_to 'Назад', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Каталог товаров</h1>

<table>
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td>
   <%= image_tag(product.image_url, :class => 'list_image', width: '155') %>
    </td>

    <td class="list_description">
      <dl>
        <dt><%= product.title %></dt>
        <dd><%= truncate(strip_tags(product.description),
               :truncate => 80) %></dd>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Просмотр', product %><br/>
      <%= link_to 'Редактировать', edit_product_path(product) %><br/>
      <%= link_to 'Удалить', product ,method: :delete, data: {confirm: 'Вы уверены?'}%>
      
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить новый продукт', new_product_path %>

app/views/products/new.html.erb
<h1>Новый продукт</h1>

<%= render 'form', product: @product %>

<%= link_to 'Назад', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Заголовок:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Аннотация:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Картинка:</strong>
  <br />
  <%= image_tag @product.image_url, width:200 %>
  <br />
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Редактировать', edit_product_path(@product) %> |
<%= link_to 'Назад', products_path %>